"""
TLS context factories used to validate the various kinds of
certificates generated by the CA.
"""

from OpenSSL.SSL import VERIFY_PEER, VERIFY_FAIL_IF_NO_PEER_CERT

from zope.interface import implementer

from twisted.web.iweb import IPolicyForHTTPS
from twisted.internet.ssl import (
    optionsForClientTLS, CertificateOptions,
    )

from pyrsistent import PRecord, field


@implementer(IPolicyForHTTPS)
class ControlServicePolicy(PRecord):
    """
    HTTPS TLS policy for validating the control service's identity, and
    providing the HTTP client's identity.

    :ivar Certificate ca_certificate: The certificate authority's
        certificate.

    :ivar PrivateCertificate client_certificate: Client's
        certificate/private key pair.
    """
    ca_certificate = field(mandatory=True)
    client_certificate = field(mandatory=True)

    def creatorForNetloc(self, hostname, port):
        return optionsForClientTLS(u"control-service",
                                   trustRoot=self.ca_certificate,
                                   clientCertificate=self.client_certificate)


class AMPContextFactory(object):
    """
    Context factory that validates AMP clients.

    Or maybe actually these'll be params:

    :ivar Certificate ca_certificate: The certificate authority's
        certificate.

    :ivar ControlCredential control_credential: The control service's
        credentials.
    """
    def __init__(self, ca_certificate, control_credential):
        key = control_credential.credential.keypair.keypair.original
        certificate = control_credential.credential.certificate.original
        self._default_options = CertificateOptions(
            privateKey=key, certificate=certificate, trustRoot=ca_certificate)

    def getContext(self):
        def verify(conn, cert, errno, depth, preverify_ok):
            if depth > 0:
                # Certificate authority chain:
                return preverify_ok
            # Now we're actually verifying certificate we care about:
            if not preverify_ok:
                return preverify_ok
            return cert.get_subject().commonName.startswith(b"node-")
        context = self._default_options.getContext()
        context.set_verify(VERIFY_PEER | VERIFY_FAIL_IF_NO_PEER_CERT,
                           verify)
        return context


# RESTAPIContextFactory is like above, just slightly different validation.
