#!/usr/bin/env python

import os
import pipes
from subprocess import check_call

GITHUB_KEYS_URL = "https://github.com/{username}.keys"

def su(username, command):
    command = u' '.join(pipes.quote(part) for part in command)
    return check_call(['su', '--login', '--command={}'.format(command), username])

def main(argv):
    [username] = argv
    # Create the user and allow them to view logs and run commands via sudo
    check_call(['adduser', '--groups=adm,wheel', username])
    # A round about way to create a .ssh directory with correct permissions
    su(username, ['ssh-keygen'])
    # Download keys to authorized_keys
    authorized_keys_path = os.path.expanduser(
        '~{username}/.ssh/authorized_keys'.format(username=username)
    )
    su(username, 
       ['curl', '--output', authorized_keys_path,
        GITHUB_KEYS_URL.format(username=username)])

    # Set the correct permissions on that file
    check_call(['chmod', '0600', authorized_keys_path])

            
if __name__ == '__main__':
    import sys
    main(sys.argv[1:])
