#!/bin/bash
# Revert the Yosemite virtualmachine to a state where homebrew has
# just been installed, start the machine and ssh into it.
set -ex

PATH="${PATH}:/Applications/VMware Fusion.app/Contents/Library"
YOSEMITE_VMX_PATH="${HOME}/Desktop/Virtual Machines.localized/OS X 10.10.vmwarevm/OS X 10.10.vmx"

vmrun revertToSnapshot "${YOSEMITE_VMX_PATH}" homebrew-clean
vmrun start "${YOSEMITE_VMX_PATH}" nogui
sleep 100
# vmrun start "${YOSEMITE_VMX_PATH}"

# ssh -o ConnectTimeout=500 ClusterHQVM@172.18.140.54
fab --timeout=200 -H ClusterHQVM@172.18.140.54 brew

vmrun stop "${YOSEMITE_VMX_PATH}" hard
