#!/usr/bin/env python2

from os import environ
from subprocess import call


def tox(tox_env):
    return call(["tox", "-e", tox_env])


BUILDERS = {
    "lint": tox,
    "docs-lint": tox,
    "docs-spelling": tox,
    "docs-linkcheck": tox,
    "docs-html": tox,
}


def main():
    builder_name = environ["FLOCKER_BUILDER"]
    builder = BUILDERS[builder_name]
    return builder(builder_name)

if __name__ == "__main__":
    raise SystemExit(main())
