#!/usr/bin/env python
# Copyright ClusterHQ Inc.  See LICENSE file for details.
"""
Build operating system packages for Flocker.

This script calls ``build-package-entrypoint`` inside a docker image.
"""

from _preamble import TOPLEVEL, BASEPATH

from admin.packaging import main

main(top_level=TOPLEVEL, base_path=BASEPATH)
