#!/usr/bin/env python
# Copyright Hybrid Logic Ltd.  See LICENSE file for details.
"""
Build operating system packages for Flocker.
"""

from _preamble import TOPLEVEL, BASEPATH

from admin.packaging import docker_main

docker_main(top_level=TOPLEVEL, base_path=BASEPATH)
