#!/usr/bin/env python
# Copyright Hybrid Logic Ltd.  See LICENSE file for details.
"""
Build operating system packages for Flocker.
"""

from _preamble import TOPLEVEL, BASEPATH

import sys

from admin.packaging import main

main(top_level=TOPLEVEL, base_path=BASEPATH)
