#!/usr/bin/env python
# Copyright ClusterHQ Inc.  See LICENSE file for details.
"""
Build operating system packages for Flocker.

This script is for use as an entry point inside a docker image.
"""

from _preamble import TOPLEVEL, BASEPATH

from admin.packaging import docker_main

docker_main(top_level=TOPLEVEL, base_path=BASEPATH)
