#!/usr/bin/env python
# Copyright ClusterHQ Inc.  See LICENSE file for details.
"""
Cleanup unused cloud resources
"""

from _preamble import TOPLEVEL, BASEPATH

import sys

if __name__ == '__main__':
    from admin.cleanup import cleanup_cloud_resources_main as main
    main(sys.argv[1:], BASEPATH, TOPLEVEL)
