#!/usr/bin/env python
# Copyright ClusterHQ Inc.  See LICENSE file for details.
"""
A CLI for provisioning a flocker cluster.
"""

from _preamble import TOPLEVEL, BASEPATH

import sys

if __name__ == '__main__':
    from twisted.internet.task import react
    from admin.cluster_provision import flocker_provision_main as main
    react(main, (sys.argv[1:], BASEPATH, TOPLEVEL))
