#!/usr/bin/env python
# Copyright Hybrid Logic Ltd.  See LICENSE file for details.
"""
Create requirements.txt and dev-requirements.txt from dependency.yml.
"""

from _preamble import TOPLEVEL, BASEPATH

import sys

if __name__ == '__main__':
    from admin.requirements import main
    main(sys.argv[1:], top_level=TOPLEVEL, base_path=BASEPATH)
