#!/usr/bin/env python
# Copyright Hybrid Logic Ltd.  See LICENSE file for details.
"""
Create a Homebrew recipe for Flocker, using the VERSION environment variable.

Invoke using e.g.:
  $ export VERSION=0.1.2
  $ ./make-homebrew-recipe > flocker-${VERSION}.rb
"""

if __name__ == '__main__':
    from admin.homebrew import main
    main()
