#!/usr/bin/env python
# Copyright ClusterHQ Inc.  See LICENSE file for details.
"""
Create a Homebrew recipe for Flocker.
"""

from _preamble import TOPLEVEL, BASEPATH

import sys

if __name__ == '__main__':
    from admin.homebrew import main
    main(sys.argv[1:], top_level=TOPLEVEL, base_path=BASEPATH)
