#!/usr/bin/env python
# Copyright ClusterHQ Inc.  See LICENSE file for details.
"""
Publish a Vagrant development box.
"""

from _preamble import TOPLEVEL, BASEPATH

import sys

if __name__ == '__main__':
    from admin.release import publish_dev_box_main as main
    main(sys.argv[1:], top_level=TOPLEVEL, base_path=BASEPATH)
