#!/usr/bin/env python
# Copyright Hybrid Logic Ltd.  See LICENSE file for details.
"""
Run the acceptance tests.
"""

from _preamble import TOPLEVEL, BASEPATH

import sys

if __name__ == '__main__':
    from admin.acceptance import main
    main(sys.argv[1:], top_level=TOPLEVEL, base_path=BASEPATH)
