#!/usr/bin/env python
# Copyright Hybrid Logic Ltd.  See LICENSE file for details.
"""
Run the cluster acceptance tests.
"""

from _preamble import TOPLEVEL, BASEPATH

import sys

if __name__ == '__main__':
    from twisted.internet.task import react
    from admin.acceptance import main
    react(main, (sys.argv[1:], BASEPATH, TOPLEVEL))
