#!/usr/bin/env python
# Copyright 2015 ClusterHQ Inc.  See LICENSE file for details.
"""
Set up a cluster.
"""

from _preamble import TOPLEVEL, BASEPATH

import sys

if __name__ == '__main__':
    from twisted.internet.task import react
    from admin.cluster_setup import main
    react(main, (sys.argv[1:], BASEPATH, TOPLEVEL))
