#!/usr/bin/env python
# Copyright Hybrid Logic Ltd.  See LICENSE file for details.
"""
Test documentation redirects.
"""

from _preamble import TOPLEVEL, BASEPATH

import sys

if __name__ == '__main__':
    from admin.release import test_redirects_main as main
    main(sys.argv[1:], top_level=TOPLEVEL, base_path=BASEPATH)
