#!/usr/bin/env python
# Copyright ClusterHQ Inc.  See LICENSE file for details.
"""
Regenerate the requirements files.
"""

from _preamble import TOPLEVEL, BASEPATH

import sys

if __name__ == '__main__':
    from admin.requirements import update_requirements_main as main
    main(sys.argv[1:], BASEPATH, TOPLEVEL)
