# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "box-cutter/centos70"
  # Update kernel
  config.vm.provision :shell, :path => "yumupdate.sh", :privileged => true
  config.vm.provision :reload
  # Configure base system
  config.vm.provision :shell, :path => "bootstrap.sh", :privileged => true
  # Prepare caches
  config.vm.provision :shell, :path => "cache.sh", :privileged => true
  # Cleanup
  config.vm.provision :shell, :path => "../cleanup.sh", :privileged => true

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  unless Vagrant.has_plugin?("vagrant-reload")
    raise "vagrant-reload plugin is not installed"
  end

  unless Vagrant.has_plugin?("vagrant-vbguest")
    # TODO can we do without this with the latest VirtualBox?
    raise "vagrant-vbguest plugin is not installed"
  end
end
