#!/usr/bin/env python2
#
# Copyright ClusterHQ Inc.  See LICENSE file for details.

"""
Publish build artifacts.

Travis calls this during the `after_script` phase of its build lifecycle.
 * https://docs.travis-ci.com/user/customizing-the-build

Set ``FLOCKER_BUILDER`` environment variable before calling this script.
"""

from os import environ
from subprocess import call, check_call
import sys

from .common import BuildHandler


def publish_staging_docs():
    """
    Copy the HTML generated by the docs-html build to an S3 bucket.
    """
    expected_variables = (
        "TRAVIS_TAG",
        "TRAVIS_PULL_REQUEST_BRANCH",
        "TRAVIS_BRANCH"
    )
    for travis_name in expected_variables:
        target_directory = environ.get(travis_name)
        if target_directory:
            break
    else:
        raise KeyError(
            "os.environ did not contain any of the expected variables",
            expected_variables
        )

    return call([
        "aws", "--region", "us-east-1", "s3", "sync",
        "--delete",
        "build/html",
        "s3://clusterhq-staging-docs/" + target_directory
    ])


def archive_artifacts(*ignored):
    check_call([
        "aws", "s3", "sync",
        "build",
        "/".join([
            # XXX Using this because the Jenkins S3 user has access to it.
            "s3://clusterhq-dev-archive/flocker/artifacts",
            environ["TRAVIS_BUILD_NUMBER"],

        ])
    ])

main = BuildHandler(
    handlers={
        "docs:html": publish_staging_docs,
        "docs": archive_artifacts,
        "acceptance": archive_artifacts,
        "": lambda *build_labels: sys.stderr.write(
            "WARNING: no handler for {}\n".format(build_labels).encode('utf8')
        )
    }
).main
