#!/opt/python/cp27-cp27m/bin/python
import argparse
import os
import sys
from subprocess import check_call

PIP = "/opt/python/cp27-cp27m/bin/pip"

parser = argparse.ArgumentParser()

parser.add_argument(
    '--infile',
    dest='infile',
    required=True,
)

args = parser.parse_args()

check_call(
    [PIP, "install", "--requirement", args.infile],
    stdout=sys.stderr
)

check_call(
    [PIP, "freeze", "--requirement", args.infile],
)
