#!/usr/bin/env python

"""

"""
import glob
import os
import shutil
from subprocess import check_call
from tempfile import NamedTemporaryFile

MANYLINUX_IMAGE = "quay.io/pypa/manylinux1_x86_64:latest"
REQUIREMENTS_IMAGE = "clusterhq/flocker_update_requirements"

requirements_directory = os.path.dirname(os.path.abspath(__file__))

check_call(
    ["docker", "pull", MANYLINUX_IMAGE]
)

check_call(
    ["docker", "build", "--tag", REQUIREMENTS_IMAGE, requirements_directory]
)

for infile in glob.glob1(requirements_directory, "*.in"):
    outfile_name = infile[:-len(".in")]
    outfile_path = os.path.join(requirements_directory, outfile_name)
    with NamedTemporaryFile(
        prefix="{}.".format(outfile_name),
        suffix=".created-by-update-requirements-entrypoint",
        dir=os.path.dirname(outfile_path),
        delete=False,
    ) as outfile:
        print "PROCESSING", infile
        check_call(
            ["docker", "run",
             "--rm",
             "--volume", "{}:/requirements".format(requirements_directory),
             "--workdir", "/requirements",
             REQUIREMENTS_IMAGE,
             "/requirements/update-requirements-entrypoint",
             "--infile", infile],
            stdout=outfile
        )
        shutil.copymode(outfile_path, outfile.name)
        os.rename(outfile.name, outfile_path)
